# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Riff' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Riff
  
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'GiphyCoreSDK'
  pod 'SwiftyGif',    '~> 4.1.0'

  target 'RiffTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RiffUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
